"""Initial database schema

Revision ID: 3b0513b9dac9
Revises: 
Create Date: 2026-08-06 11:41:21.933588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b0513b9dac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('name'))
        batch_op.create_index(batch_op.f('ix_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_index('idx_product_brand_category', ['brand', 'category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('recommendation_score',
               existing_type=mysql.DECIMAL(precision=4, scale=3),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('shopping_planner', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'active', 'completed'),
               type_=sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', name='planner_status'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_shopping_planner_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_planner_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('user', 'admin'),
               type_=sa.Enum('USER', 'ADMIN', name='user_roles'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('USER', 'ADMIN', name='user_roles'),
               type_=mysql.ENUM('user', 'admin'),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('shopping_planner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_planner_user_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_planner_created_at'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', name='planner_status'),
               type_=mysql.ENUM('draft', 'active', 'completed'),
               existing_nullable=False)

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_product_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_created_at'))
        batch_op.alter_column('recommendation_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=mysql.DECIMAL(precision=4, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_created_at'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index('idx_product_brand_category')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_available')
        batch_op.drop_column('slug')
        batch_op.drop_column('sku')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_history_created_at'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_created_at'))
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_user_id'))
        batch_op.drop_index(batch_op.f('ix_cart_product_id'))
        batch_op.drop_index(batch_op.f('ix_cart_added_at'))

    # ### end Alembic commands ###
