"""Add OTP email verification and forgot password columns to User model

Revision ID: decc4437581f
Revises: 3b0513b9dac9
Create Date: 2026-08-06 12:35:44.262224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decc4437581f'
down_revision = '3b0513b9dac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_otp_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_otp_expiry')
        batch_op.drop_column('reset_otp')
        batch_op.drop_column('verification_otp_expiry')
        batch_op.drop_column('verification_otp')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
